"""
Mapping of domain exception error codes to HTTP status codes.
"""

from fastapi import status

ERROR_STATUS_MAP = {
    # Authentication & Authorization
    "UNAUTHORIZED": status.HTTP_401_UNAUTHORIZED,
    "INVALID_TOKEN": status.HTTP_401_UNAUTHORIZED,
    "TOKEN_EXPIRED": status.HTTP_401_UNAUTHORIZED,
    "AUTHENTICATION_ERROR": status.HTTP_401_UNAUTHORIZED,
    "INVALID_CREDENTIALS": status.HTTP_401_UNAUTHORIZED,
    "FORBIDDEN": status.HTTP_403_FORBIDDEN,
    "PERMISSION_DENIED": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_INACTIVE": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_PENDING_APPROVAL": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_UNVERIFIED": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_LOCKED": status.HTTP_429_TOO_MANY_REQUESTS,
    "TOO_MANY_ATTEMPTS": status.HTTP_429_TOO_MANY_REQUESTS,
    "USER_NOT_IN_ORGANIZATION": status.HTTP_403_FORBIDDEN,
    # Validation & Input Errors
    "VALIDATION_ERROR": status.HTTP_422_UNPROCESSABLE_ENTITY,
    "INVALID_INPUT": status.HTTP_422_UNPROCESSABLE_ENTITY,
    "INVALID_SUGGESTION_DATA": status.HTTP_400_BAD_REQUEST,
    "BAD_REQUEST": status.HTTP_400_BAD_REQUEST,
    "CLOSED_TICKET": status.HTTP_400_BAD_REQUEST,
    "INVALID_OTP": status.HTTP_400_BAD_REQUEST,
    "INVALID_RESET_CODE": status.HTTP_400_BAD_REQUEST,
    "RESET_TOKEN_EXPIRED": status.HTTP_400_BAD_REQUEST,
    "PASSWORD_REUSE_ERROR": status.HTTP_400_BAD_REQUEST,
    "INVALID_FILE_TYPE": status.HTTP_400_BAD_REQUEST,
    "FILE_TOO_LARGE": status.HTTP_400_BAD_REQUEST,
    "NO_FIELDS_TO_UPDATE": status.HTTP_400_BAD_REQUEST,
    # Resource Errors
    "NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "SOURCE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "RESOURCE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    # Conflict & Duplicate Errors
    "EMAIL_ALREADY_EXISTS": status.HTTP_409_CONFLICT,
    "RESOURCE_EXISTS": status.HTTP_409_CONFLICT,
    "DUPLICATE_ENTRY": status.HTTP_409_CONFLICT,
    "DUPLICATE_URL": status.HTTP_409_CONFLICT,
    "USER_ALREADY_REGISTERED": status.HTTP_409_CONFLICT,
    "REGISTRATION_PENDING": status.HTTP_409_CONFLICT,
    "RESOURCE_LOCKED": status.HTTP_423_LOCKED,
    # Rate Limiting
    "RATE_LIMIT_EXCEEDED": status.HTTP_429_TOO_MANY_REQUESTS,
    # Server Errors
    "INTERNAL_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PROCESSING_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "INTERNAL_SERVER_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "HTTP_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Service Availability
    "SERVICE_UNAVAILABLE": status.HTTP_503_SERVICE_UNAVAILABLE,
    "DEPENDENCY_ERROR": status.HTTP_503_SERVICE_UNAVAILABLE,
    # Timeout
    "TIMEOUT": status.HTTP_504_GATEWAY_TIMEOUT,
    # Method Not Allowed
    "METHOD_NOT_ALLOWED": status.HTTP_405_METHOD_NOT_ALLOWED,
    # OAuth & Authentication Flow
    "OAUTH_FLOW_ERROR": status.HTTP_401_UNAUTHORIZED,
    "OAUTH_STATE_INVALID": status.HTTP_400_BAD_REQUEST,
    "OAUTH_TOKEN_INVALID": status.HTTP_400_BAD_REQUEST,
    "OAUTH_TOKEN_EXCHANGE_FAILED": status.HTTP_401_UNAUTHORIZED,
    "OAUTH_TOKEN_VERIFICATION_FAILED": status.HTTP_401_UNAUTHORIZED,
    "MISSING_ID_TOKEN": status.HTTP_401_UNAUTHORIZED,
    "MISSING_EMAIL": status.HTTP_400_BAD_REQUEST,
    "INVALID_CLIENT": status.HTTP_400_BAD_REQUEST,
    # Matching Engine
    "COMMENT_REQUIRED": status.HTTP_400_BAD_REQUEST,
    "ALREADY_SWIPED": status.HTTP_409_CONFLICT,
    "NOT_YOUR_MATCH": status.HTTP_403_FORBIDDEN,
    "MATCH_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "PROFILE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "FEEDBACK_ALREADY_SUBMITTED": status.HTTP_409_CONFLICT,
    "DAILY_LIMIT_EXCEEDED": status.HTTP_429_TOO_MANY_REQUESTS,
    "SUPER_LIKE_LIMIT_EXCEEDED": status.HTTP_429_TOO_MANY_REQUESTS,
    "LIMIT_EXCEEDED": status.HTTP_429_TOO_MANY_REQUESTS,
}
